### ISSUE TITLE
Parsing MY_P, MY_PN and MY_PV

### ISSUE THREAD

**Issue by monsieurp** [gentoo/java-ebuilder#1]
Very low priority issue at this point but some ebuilds use other variables such as MY_PN, MY_PV, etc.

**Comment by fordfrog** [comment]
in fact variables that occur in the SLOT are:
- ${PV:0:3} (lucene)
- ${SV} (scala)
- $(get_version_component_range 1-2) (sys-libs/db)

no other variables currently appear in the cache file so only handling of these is needed atm. also, those mentioned above cannot appear in SLOT variable.

**Comment by fordfrog** [comment]
all the occurances of $ in SLOT string in cache file has been resolved in commit da4487f8b130526bffc6dff8b8e5ad400d6d4bc2. when new cases appear resulting in $ being in cache file again, we open new bug.
